### ISSUE TITLE
Checked in api key

### ISSUE THREAD

**Issue by emmonspired** [mbrooks/gif-capture#89]
Hey, just wanted to let you know I noticed you checked in an API key.

**Comment by mbrooks** [comment]
First off, Thanks for letting me know! 

Do you know if this the fire base API key? If so it’s designed to be public, however if it’s letting you do something you shouldn’t be able to do, then that may be an indication that I configured it wrong on my side definitely.

https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public
